version: "3"
services:

  bellcom.db:
    container_name: bellcom.db
    image: mariadb:10.5.8-focal
    volumes:
      - ./configs/db:/etc/mysql/conf.d
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=bellcom
      - MYSQL_ROOT_PASSWORD=change-password


  bellcom.backend:
    container_name: bellcom.backend
    image: bellcom.backend:local
    volumes:
      - ./../storage/app/public:/var/www/html/storage/app/public/
    environment:
      - TZ=UTC
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 7000:80

  bellcom.pma:
    container_name: bellcom.pma
    image: phpmyadmin/phpmyadmin:5.0.4
    links:
      - bellcom.db:db
    environment:
      - TZ=UTC
      - UPLOAD_LIMIT=2G
    ports:
      - 7010:80